env:
  global:
  - PUB_DIR=public
language: go
go:
- 1.4
before_install:
- openssl aes-256-cbc -K $encrypted_f80b1531dee6_key -iv $encrypted_f80b1531dee6_iv
  -in deploy_key.enc -out deploy_key -d
install:
- go get github.com/spf13/hugo
script: hugo
after_success: bash ./deploy.sh
